cook = [
    {
        "Ingredients": ["250g of rice flour", "500ml of water", "1 teaspoon of salt", "1 teaspoon of sugar", "Dried shrimp, pork, fried shallots, rice crackers, seasoning, and fresh herbs for filling"],
        "Steps": ["Rinse and chop the ingredients for the filling into small pieces", "Boil the water in a pot and add the dried shrimp, pork, and seasoning to cook until well done. Remove from heat and drain excess water", "Mix rice flour, salt, and sugar with water to form a smooth batter", "Grease the bottom of small ceramic or metal cups with oil", "Fill each cup with batter up to 3/4 full, and then place the cups on a steaming tray", "Steam the cups of batter for about 5 minutes until the batter is cooked and firm", "Remove the cups from the steamer and top each with the prepared filling and garnish with fried shallots, rice crackers, and fresh herbs"]
    },
    {
        "Ingredients": ["500g tapioca starch", "350ml boiling water", "400g shrimp, peeled and deveined", "200g lean pork, minced", "2 shallots, finely chopped", "Salt and pepper to taste", "Dipping sauce: fish sauce, sugar, lime juice, chili, and garlic."],
        "Steps": ["Place tapioca starch in a mixing bowl", "Boil water and add it to the mixing bowl. Mix well until the dough forms", "Knead the dough until it becomes smooth and elastic", "Divide the dough into small balls and roll each into thin circles around 6-7 cm in diameter", "Mix minced pork, chopped shallots, salt, and pepper in a bowl. Add a spoonful of the mixture onto the center of each tapioca circle", "Add a shrimp on top of the minced pork mixture", "Fold the tapioca dough in half to create a semi-circle shape. Press the edges together to seal", "Boil water in a pot. Place the banh bot loc in a steamer basket and steam for 5-7 minutes until they become transparent"]
    },
    {
        "Ingredients": ["300g rice flour", "200ml water", "200ml coconut milk", "1/2 teaspoon salt", "Green onions, Vietnamese coriander, pork floss, quail eggs, and/or shrimp for toppings", "Dipping sauce: fish sauce, sugar, lime juice, chili, and garlic"],
        "Steps": ["Mix rice flour, water, coconut milk and salt in a mixing bowl until the batter becomes smooth", "Preheat the banh can mold over medium heat. Grease the mold with oil or butter", "Pour the batter into each mold's cavity until 3/4 full", "Add toppings on the top of the batter such as quail eggs, shrimp, pork floss or green onions", "Cover the mold and cook for around 5-6 mins until the batter is cooked and turns light brown", "Use a skewer stick to gently remove the banh can from the mold", "Serve hot with dipping sauce"]
    },
    {
        "Ingredients": ["300g tapioca flour", "150g rice flour", "500ml water", "1 teaspoon salt", "500g pork bones (or chicken bones)", "500g pork belly, sliced", "1 onion, halved", "1 tablespoon fish sauce", "1 teaspoon sugar", "Green onions, cilantro, bean sprouts, and/or fried shallots for toppings"],
        "Steps": ["In a mixing bowl, combine tapioca flour, rice flour, salt and water. Mix well until the dough becomes smooth", "Spread out the dough on a wet cutting board and cut into thin noodles", "In a pot, add pork bones, pork belly, onion, fish sauce, sugar and enough water to cover ingredients", "Bring to a boil then let it simmer for about 45-60 mins until the pork belly is cooked and tender, and the broth is flavorful", "Remove pork belly from the pot and slice thinly", "Boil a pot of water and cook the banh canh noodles for a few minutes", "Rinse the cooked noodles with cold water, drain it, and then transfer it to a bowl", "Add the sliced pork belly and ladle the hot broth over the noodles", "Add toppings such as green onions, cilantro, bean sprouts, and fried shallots"]
    },
    {
        "Ingredients": ["1kg glutinous rice", "500g pork belly", "200g mung beans", "20 Dong leaves (or banana leaves)", "2 teaspoons salt", "1 teaspoon black pepper", "1 tablespoon sugar"],
        "Steps": ["Soak glutinous rice in water overnight", "Wash mung beans and soak for a few hours", "Season pork belly with salt, black pepper, and sugar. Let it rest for about 1 hour", "Cut pork belly into rectangular chunks", "Boil mung beans until they become soft, then mash them into a paste", "Clean Dong leaves by washing them with soap and water. Wipe them dry", "Fold the Dong leaves into a square container, and place them in one or two layers", "Add a layer of glutinous rice into the container until it evenly covers the Dong leaves", "Add a layer of mashed mung beans, then the pork belly pieces on top of that", "Add another layer of glutinous rice on top of the pork belly to cover it", "Fold the Dong leaves tightly around the rice to form a square shape", "Tie the Banh Chung tightly with a string or banana leaves", "Boil the Banh Chung in a large pot of water over medium-high heat for about 4-5 hours, making sure the water remains at the same level throughout the cooking process", "Remove the Banh Chung from the pot and let it cool down", "Cut Banh Chung into thick slices and serve with some vegetables or dipping sauce"]
    },
    {
        "Ingredients": ["250g rice flour", "1 tablespoon cornstarch", "500ml water", "1/2 teaspoon salt", "1 teaspoon cooking oil", "1/2 pound ground pork", "1/4 cup dried wood ear mushrooms, soaked in water, and thinly sliced", "1/4 cup dried shredded shrimp, soaked in water, drained, and chopped", "1/4 cup fried shallots", "2 tablespoons fish sauce", "1 tablespoon soy sauce", "1 teaspoon sugar", "1/4 teaspoon black pepper"],
        "Steps": ["In a mixing bowl, mix rice flour, cornstarch, water, salt, and cooking oil. Stir well until the batter becomes smooth", "In a pan, cook ground pork until it's no longer pink. Add wood ear mushrooms, dried shrimp, fish sauce, soy sauce, sugar, and black pepper. Cook for about 5 minutes", "Heat a non-stick frying pan over medium heat", "Grease the pan with oil and pour 1/4 cup of the batter evenly into the center of the pan", "Spread the batter to form a thin layer and make sure it's even", "Cover the pan with a lid and cook for about 1 minute", "Remove the cover, add 1 tablespoon of filling on the surface of the batter, and then fold the banh cuon in half", "Use a spatula to remove the banh cuon from the pan and place it on a plate", "Repeat the process until all the batter and filling are used up", "Serve the banh cuon hot with some fried shallots, herbs, and dipping sauce"]
    },
    {
        "Ingredients": ["1 cup rice flour", "1/4 cup glutinous rice flour", "4 cups water", "1/2 teaspoon salt", "1 teaspoon vegetable oil", "Fried garlic, sliced green onions, crispy fried shallots, and/or fish sauce for toppings"],
        "Steps": ["In a mixing bowl, mix rice flour, glutinous rice flour, salt, and water. Stir well until the batter becomes smooth", "Heat a non-stick frying pan over medium heat", "Grease the pan with oil and pour the batter into the pan", "Stir the batter continuously until it starts to thicken and become sticky", "Turn down the heat to low and cover the pan with a lid. Cook for an additional 5-10 minutes until the batter fully cooks into a solid cake", "Remove the cake from the pan and let it cool down", "Cut the cake into squares or triangles", "Serve the banh duc hot with some fried garlic, sliced green onions, crispy fried shallots, and/or fish sauce"]
    },
    {
        "Ingredients": ["2 cups rice flour", "5 cups water", "1/2 pound ground pork", "1/4 cup wood ear mushrooms, soaked in water, and thinly sliced", "1/4 cup dried shrimp, soaked in water, drained, and chopped", "1/4 cup fried shallots", "2 tablespoons fish sauce", "1 tablespoon soy sauce", "1 tablespoon vegetable oil", "1/2 teaspoon salt", "Banana leaves"],
        "Steps": ["In a mixing bowl, mix rice flour and water. Stir well until the batter becomes smooth", "In a pan, cook ground pork until it's no longer pink. Add wood ear mushrooms, dried shrimp, fish sauce, soy sauce, fried shallots, vegetable oil, and salt. Cook for about 10 minutes until all the ingredients are well-mixed and fragrant", "Wash and dry banana leaves, and then cut them into 5-inch squares", "Put a banana leaf square on one hand and scoop about 2 tablespoons of batter on it. Use a spoon to flatten the batter and create a small, deep concave in the center", "Add 1 tablespoon of filling into the concave", "Gather the edges of the banana leaf around the batter and filling, and then flatten and press the contents into a small package", "Repeat the process until all the batter and filling are used up", "Steam the banh gio for about 30 minutes until the batter is cooked and the filling is hot", "Remove the banh gio from the steamer and let it cool down a little bit", "Remove the banana leaves and serve the banh gio hot with some herbs and dipping sauce"]
    },
    {
        "Ingredients": ["1 cup rice flour", "1/4 cup cornstarch", "2 cups coconut milk", "1/2 teaspoon turmeric powder", "1/2 teaspoon salt", "1/4 teaspoon sugar", "1/4 teaspoon pepper", "1 pound small shrimp, peeled and deveined", "1/4 cup scallions, finely chopped", "1/4 cup fried shallots", "Cooking oil"],
        "Steps": ["In a mixing bowl, mix rice flour, cornstarch, coconut milk, turmeric powder, salt, sugar, and pepper. Stir well until the batter becomes smooth", "In a non-stick pan, heat a small amount of cooking oil over medium heat", "Add a little bit of batter to each mold of the banh khot pan and add a shrimp on top. Cook for about 2-3 minutes or until the bottom of the banh kho is crispy and golden", "Add more batter into each mold, covering the shrimp", "Cook the banh khot for about 5 minutes or until the surface is cooked and the edges are crispy", "Use a toothpick or a skewer to remove the banh khot from the pan", "Repeat the process until all the batter and shrimp are used up", "Serve the banh khot hot with some chopped scallions, fried shallots, and dipping sauce"]
    },
    {
        "Ingredients": ["One baguette", "1/3 cup mayonnaise", "1 tablespoon sriracha sauce (optional)", "1/2 pound pork belly, sliced into thin pieces", "2 tablespoons soy sauce", "2 tablespoons honey", "1 tablespoon vegetable oil", "1/2 carrot, peeled and julienned", "1/2 cucumber, thinly sliced", "Handful of cilantro", "Pickled daikon and carrot"],
        "Steps": ["Preheat oven to 350°F. Cut the baguette in half lengthwise and spread mayonnaise onto one side of the bread and sriracha sauce onto the other", "In a pan, heat the vegetable oil and cook the pork belly until it's lightly golden. Add the soy sauce and honey and cook for an additional 5 minutes or until the pork belly is well-cooked and caramelized", "Add the pork belly onto the baguette, then add the pickled daikon and carrot on top", "Add the sliced cucumber, a handful of cilantro, and close the sandwich", "Wrap the sandwich in foil. Put it in the oven for about 10 minutes", "Remove the sandwich from the foil and slice it in half", "Serve hot with a side of pickled vegetables"]
    },
    {
        "Ingredients": ["2 cups glutinous rice flour", "1/4 cup sugar", "3/4 cup water", "1/2 cup unsalted butter, at room temperature", "1/4 teaspoon salt", "2 cups mung bean paste", "1 egg yolk, beaten"],
        "Steps": ["In a mixing bowl, mix glutinous rice flour, sugar, salt, and water. Knead the dough until it's smooth and elastic", "Add the unsalted butter to the dough and knead it until the butter is well-incorporated and the dough becomes shiny", "Divide the dough into small portions and flatten each portion into a circle, about 1/4 inch thick", "Spoon 1 tablespoon of mung bean paste onto the center of the dough circle", "Lift the sides of the dough and gather them together, pinching and twisting the top to seal in the filling", "Preheat the oven to 375°F", "Place the sealed pastry balls on a baking sheet lined with parchment paper", "Brush the top of each pastry ball with beaten egg yolk", "Bake the banh pia for about 20-25 minutes, or until the top is golden brown", "Remove the banh pia from the oven and let them cool before serving"]
    },
    {
        "Ingredients": ["4 cups glutinous rice", "1/4 cup dried mung bean", "2 teaspoons salt", "1 tablespoon sugar", "1/2 pound pork belly, sliced into thin pieces", "2 tablespoons fish sauce", "1 teaspoon black pepper", "1 tablespoon vegetable oil", "Banana leaves (if available)", "Cooking twine"],
        "Steps": ["Soak the glutinous rice in water for at least 4 hours or overnight. Drain the water and set aside", "Soak the dried mung bean in water for at least 2 hours. Drain the water and set aside", "In a pan, heat the vegetable oil and cook the pork belly until it's lightly golden. Add the fish sauce and black pepper and cook for an additional 5 minutes or until the pork belly is well-cooked and caramelized", "In a mixing bowl, mix the glutinous rice with salt and sugar", "Cut the banana leaves into rectangular shapes (about 2 feet long and 1 foot wide)", "Place 2-3 banana leaves on top of each other, then fold them in half. This will make a strong wrapping for the banh tet", "Place a layer of rice on the banana leaves, then add a layer of mung bean and a layer of pork belly", "Repeat the layers until all the ingredients are used up, then cover the filling with another layer of rice, making sure everything is evenly distributed", "Fold the banana leaves over the rice and pork filling, tightly wrapping it like a log", "Tie the banh tet tightly with cooking twine", "In a large pot, boil enough water to submerge the banh tet completely", "Add the banh tet to the pot and boil for about 3-4 hours, or until the banana leaves turn dark green and the rice is fully cooked", "Remove the banh tet from the pot and let them cool for at least 30 minutes", "Remove the banana leaves and slice the banh tet into bite-sized pieces before serving"]
    },
    {
        "Ingredients": ["Rice paper (banh trang)", "1/2 cup green onion, thinly sliced", "1/2 cup dried shrimp, soaked and chopped", "1/2 cup pork floss", "1/4 cup roasted peanuts, chopped", "1 tablespoon sesame seeds", "1/4 teaspoon salt", "2 tablespoons vegetable oil", "Your choice of sauce: chili sauce, soy sauce, or mayonnaise"],
        "Steps": ["Preheat the oven grill to high", "Cut the rice paper into squares (about 6 inches or desired size)", "Brush each side of the rice paper with vegetable oil and sprinkle a pinch of salt onto each side", "Place the rice paper onto a baking sheet and grill them in the oven for about 5 minutes or until they turn crispy and golden brown", "Remove the rice paper from the oven and sprinkle green onions, dried shrimp, and pork floss onto the top side", "Sprinkle chopped peanuts, sesame seeds, and a pinch of salt onto the top side of the rice paper", "Return the rice paper to the oven, grill for additional 2-3 minutes or until the toppings are lightly toasted", "Remove the banh trang nuong from the oven and let them cool for a few minutes", "Serve with your choice of sauce: chili sauce, soy sauce or mayonnaise"]
    },
    {
        "Ingredients": ["1 cup rice flour", "1/4 cup cornstarch", "1/2 teaspoon turmeric powder", "1/2 teaspoon salt", "1 1/2 cup water", "1/2 cup coconut milk", "1 pound pork belly, sliced into thin pieces", "1/2 pound medium shrimp, peeled and deveined", "1 yellow onion, thinly sliced", "2 cups bean sprouts", "Vegetable oil for cooking", "Lettuce leaves and herbs (mint, basil, cilantro) for serving", "Dipping sauce (nuoc cham) for serving"],
        "Steps": ["In a mixing bowl, whisk together rice flour, cornstarch, turmeric powder, and salt until well combined", "Add water and coconut milk to the mixing bowl and mix until it turns into a smooth batter. Set aside", "In a pan, heat up some vegetable oil on medium-high heat and cook the sliced pork belly until it turns slightly golden and crispy. Remove from heat and set aside", "In the same pan, stir-fry the shrimp, yellow onion, and bean sprouts until cooked through. Set aside", "Heat up a non-stick skillet on medium-high heat. Pour a ladle of the batter onto the skillet and spread it out into a thin layer", "Add cooked pork belly, shrimp, onion, and bean sprouts on one side of the pancake", "Cover the pan with a lid and let the pancake cook for about 2-3 minutes or until it becomes crispy and golden brown", "Carefully fold the other side of the pancake over the filling and transfer it to a serving plate. Repeat the process with the remaining batter and fillings", "Serve the banh xeo with fresh lettuce leaves and herbs, and dipping sauce on the side"]
    },
    {
        "Ingredients": ["1 pound beef shank", "1/2 pound pork belly", "1/2 pound pork leg bone", "1 tablespoon shrimp paste", "2-3 tablespoons chili oil", "6-8 lemongrass stalks, bruised", "2 onions, peeled and charred", "2 tablespoons fish sauce", "1 tablespoon sugar", "1 tablespoon salt", "1 tablespoon paprika", "1 package (14 oz) of Bun Bo Hue Noodles (or other similar noodles)", "4-6 cups water", "1/4 cup vinegar", "1/2 cup thinly sliced onions", "1/2 cup cilantro leaves", "Lime wedges and chili peppers (optional)"],
        "Steps": ["In a large pot, blanch the beef shank, pork belly, and pork leg bone in boiling water for 5 minutes to remove any impurities. Rinse with cold water and set aside", "In the same pot, heat up 2 tablespoons of vegetable oil and add shrimp paste, chili oil and sauté until fragrant", "Add the lemongrass stalks, charred onions and sauté for another 2-3 minutes", "Add the beef shank, pork belly, pork leg bone, fish sauce, sugar, salt, paprika and water to the pot. Bring the pot to a boil, then reduce the heat to low and let it simmer for about 2-3 hours or until the meats are tender and the broth is rich and flavorful", "Remove the meats from the pot and let them cool. Slice the beef shank and pork belly into thin pieces and set aside", "In a pot, cook the noodles for about 7-9 minutes or until they are tender. Drain and rinse with cold water", "In a small bowl, mix the vinegar and thinly sliced onions together and let it marinate for about 10 minutes", "To assemble, place a serving of noodles into a bowl and top it with the sliced beef shank, pork belly, and onions. Ladle the hot broth over the top of the noodles, then garnish with cilantro leaves, lime wedges and chili peppers (if desired)"]
    },
    {
        "Ingredients": ["1 package of firm tofu", "Rice vermicelli noodles (bun)", "1/2 cup fermented shrimp paste sauce (mam tom)", "1/3 cup white vinegar", "1/4 cup sugar", "1/4 cup fish sauce", "2 cloves garlic, minced", "1-2 Thai chili peppers, minced (optional)", "A small bunch of mint leaves, chopped", "A small bunch of cilantro leaves, chopped", "1/2 cup roasted peanuts, chopped", "1/4 cup fried shallots"],
        "Steps": ["Cut the firm tofu into small cubes and lightly deep-fry in hot oil until they turn golden brown. Drain on paper towels and set aside", "Cook the rice vermicelli noodles according to the package instructions until they are tender. Drain and rinse with cold water. Set aside", "In a mixing bowl, whisk together fermented shrimp paste, white vinegar, sugar, fish sauce, minced garlic, and chili peppers (if using) until well combined", "Add some hot water and mix until the sauce reaches a desired consistency", "To assemble, place a serving of cooked noodles onto a plate. Add some crispy fried tofu cubes on the side, then drizzle the fermented shrimp paste sauce over the noodles", "Garnish with chopped mint leaves, cilantro leaves, roasted peanuts, and fried shallots"]
    },
    {
        "Ingredients": ["1 pound pork belly, sliced into thin pieces", "1 pound shrimp, peeled and deveined", "1/2 pound squid, cleaned and sliced into rings", "Rice vermicelli noodles (bun)", "4 tablespoons fermented fish paste (mam)", "4 tablespoons tamarind pulp", "1 tablespoon sugar", "1 tablespoon chicken or beef bouillon powder", "1 tablespoon annatto seeds", "4 cloves garlic, minced", "2 shallots, thinly sliced", "2-3 Thai chili peppers, chopped (optional)", "Assorted vegetables, such as bean sprouts, shredded lettuce, mint leaves, basil leaves, and cilantro", "Lime wedges and sliced chili peppers (optional)"],
        "Steps": ["In a large pot, add pork belly slices and fill with enough water to cover the meat. Bring the pot to a boil and let it simmer for about 20 minutes or until the pork is cooked through. Remove from heat and set aside", "In a pan, heat up some oil, and add minced garlic, sliced shallots, and annatto seeds. Cook until fragrant for about 1-2 minutes", "Add the fermented fish paste (mam) and stir-fry for another 2-3 minutes", "Add 6-8 cups of water tamarind pulp, sugar, bouillon powder, and chili peppers (if using) into the pot. Stir well and bring it to a boil", "Add the pork slices, shrimp, and squid into the pot and let it simmer for another 10-15 minutes or until the seafood is cooked through and tender", "Cook the rice vermicelli noodles according to the package instructions. Drain and rinse with cold water", "To assemble, place a serving of cooked rice vermicelli noodles into a bowl and top with some of the cooked pork, shrimp and squid. Ladle hot broth with pieces of seafood over the top of the noodles. Garnish with chopped vegetables, lime wedges, and sliced chili peppers (if desired)"]
    },
    {
        "Ingredients": ["1 pound ground pork", "1/2 pound shrimp, peeled and deveined", "1/2 cup crab or shrimp paste", "4-5 ripe tomatoes, quartered", "1 onion, peeled and sliced", "2 tablespoons fish sauce", "1 tablespoon sugar", "8 cups water", "1 package of round rice vermicelli noodles (bun)", "1/2 cup chopped green onions", "1/2 cup chopped cilantro", "1/2 cup fried shallots", "1 lime, cut into wedges"],
        "Steps": ["In a large pot, add water, tomatoes and onion and bring it to a boil. Let it simmer for about 30 minutes or until the tomatoes are soft and tender", "Remove the tomatoes and onion from the pot and blend them until smooth. Strain the mixture through a fine-mesh sieve into a separate bowl, and discard the solids", "Add the ground pork, shrimp, and crab or shrimp paste into the pot with the tomato broth. Stir well and simmer on low heat for about 15-20 minutes or until the pork and shrimp are cooked through", "Add fish sauce, sugar, and additional salt to taste", "Cook the rice vermicelli noodles according to the package instructions. Drain and rinse with cold water", "To assemble, place a serving of cooked rice vermicelli noodles into a bowl and top with the hot tomato broth and meat mixture. Garnish with chopped green onions, cilantro, fried shallots, and a wedge of lime"]
    },
    {
        "Ingredients": ["1 package of round rice vermicelli noodles (bun)", "1/2 cup carrots, julienned", "1 pound pork shoulder, sliced into thin pieces", "1 stalk lemongrass, minced", "3 cloves garlic, minced", "2 shallots, minced", "2 tablespoons fish sauce", "2 tablespoons soy sauce", "1 tablespoon honey", "1 tablespoon vegetable oil", "1/4 cup fish sauce", "1/4 cup rice vinegar", "1/4 cup sugar", "1/2 cup water", "1 garlic clove, minced", "Nuoc cham dipping sauce (recipe below)"],
        "Steps": ["In a mixing bowl, add minced lemongrass, garlic, shallots, fish sauce, soy sauce, honey, and vegetable oil. Mix well and add the sliced pork shoulder. Cover the bowl with plastic wrap and marinate in the fridge for 1-2 hours", "Preheat your grill or grill pan over medium-high heat. Grill the marinated pork slices for about 2-3 minutes per side or until they are cooked through with a nice char on the outside", "Cook the rice vermicelli noodles according to the package instructions. Drain and rinse with cold water", "To assemble, place a serving of cooked rice vermicelli noodles into a bowl and top with some sliced grilled pork. Add some carrots, cucumbers, chopped mint and cilantro leaves, and chopped roasted peanuts on top", "Drizzle the nuoc cham dipping sauce all over the top of the noodles and pork", "Serve with additional herbs, lime wedges and chili pepper slices on the side"]
    },
    {
        "Ingredients": ["2-3 catfish steaks or fillets, about 1 pound", "1/4 cup fish sauce", "1/4 cup sugar", "1/4 cup unsweetened coconut soda (or water)", "1 tablespoon vegetable oil", "3-4 cloves garlic, minced", "1 small shallot, minced", "1 red chili pepper, sliced (optional)", "1/2 teaspoon black pepper", "1-2 green onions, chopped", "Cilantro leaves, chopped for garnish"],
        "Steps": ["In a small saucepan, heat up the sugar over medium heat until it melts and turns a rich brown color, about 5-7 minutes. Be sure to watch the sugar carefully so it does not burn. Once the sugar has melted and caramelized, add fish sauce and coconut soda. Stir well and set aside", "In a clay pot or large saucepan, heat up the vegetable oil over medium heat. Add minced garlic, shallot, and sliced chili pepper (if using) and sauté for about 1-2 minutes until fragrant", "Add the caramelized fish sauce mixture to the pot and bring it to a simmer over low heat for 5-7 minutes", "Add the catfish steaks/fillets to the pot, along with black pepper. Spoon some of the sauce over the fish and make sure it is submerged in the sauce. Turn the heat to medium-low, cover the pot and let it cook for 20-25 minutes until the fish is cooked through and tender", "Add chopped green onions and cook for another 5 minutes", "Garnish with cilantro leaves and serve hot with steamed rice"]
    },
    {
        "Ingredients": ["1-2 cups of fish fillet, cut into bite-size pieces (can use catfish, tilapia, or any other white, firm-fleshed fish)", "1/4 cup tamarind pulp, soaked in 1 cup hot water and strained to get juice", "4 cups water", "1 tablespoon vegetable oil", "2 cloves garlic, minced", "1 small shallot, minced", "1 tablespoon sugar", "1 tablespoon fish sauce", "1/4 teaspoon salt", "1 small tomato, cut into wedges", "1/4 pineapple, peeled and cut into bite-size pieces", "1-2 green onions, chopped", "1-2 Thai chili peppers, sliced (optional)", "1/4 cup chopped cilantro leaves"],
        "Steps": ["In a large pot, add the tamarind juice and water and bring it to a boil", "Add minced garlic and shallot to a sauté pan with vegetable oil and sauté until fragrant", "Add the fish pieces to the pot with the tamarind juice mixture and simmer for 3-5 minutes until cooked through", "Add the sugar, fish sauce, salt, tomato, and pineapple to the pot and simmer for another 5-7 minutes until the vegetables are tender", "Add the green onions and chili pepper slices (if using) and simmer for another minute", "Garnish with cilantro leaves and serve hot with steamed rice"]
    },
    {
        "Ingredients": ["8 oz dried cao lầu noodles (can substitute with udon noodles or thicker rice noodles)", "1/2 lb pork loin, sliced into thin pieces", "1 cup fresh bean sprouts", "1/4 cup scallions, sliced thinly", "1/4 cup mint leaves", "1/4 cup unsalted roasted peanuts, crushed", "2 tablespoons fish sauce", "2 tablespoons soy sauce", "1 tablespoon vegetable oil", "1/2 teaspoon black pepper", "1 clove garlic, minced", "4 cups chicken or pork broth", "2 tablespoons soy sauce", "1/2 teaspoon five spice powder"],
        "Steps": ["In a mixing bowl, combine all the marinade ingredients and add sliced pork. Mix well and set aside for at least 20-30 minutes", "Cook the cao lầu noodles according to the package instructions, drain and rinse with cold water", "In a large soup pot, heat up chicken or pork broth over medium-high heat. Add soy sauce, hoisin sauce, fish sauce, and five spice powder. Simmer for 5-7 minutes and then reduce the heat to low", "In a separate pan, heat up a tablespoon of oil over medium-high heat and then add the marinated pork slices. Cook the pork for 3-5 minutes until cooked through and caramelized on the outside", "To assemble, place a serving of cooked cao lầu noodles at the bottom of each bowl. Add a handful of fresh bean sprouts on top of the noodles. Place a few slices of cooked pork on top of the bean sprouts and pour some of the broth over the top", "Garnish each serving with scallions, mint, cilantro, fried shallots, and crushed roasted peanuts"]
    },
    {
        "Ingredients": ["1 cup uncooked white rice", "8 cups water or chicken broth", "1/2 lb pork liver, sliced into thin pieces", "1/2 lb pork heart, sliced into thin pieces", "1/2 lb pork kidney, sliced into thin pieces", "1/2 lb ground pork", "2 tablespoons vegetable oil", "1 small onion, chopped", "4 gloves garlic, chopped", "1 tablespoon fish sauce", "1 teaspoon sugar", "1/2 teaspoon salt", "1/4 teaspoon black pepper", "1 tablespoon chopped scallions", "1 tablespoon chopped cilantro", "Fried garlic", "Fried shallots", "Sliced chili peppers", "Lime wedges"],
        "Steps": ["Rinse the rice with tap water and drain. In a large pot, bring the rice and water to a boil, then reduce heat to low and simmer for 40-45 minutes, stirring occasionally to prevent sticking and burning", "In a pan, heat up the oil over medium-high heat. Add the onion and garlic and sauté until fragrant", "Add the ground pork to the pan and cook until browned", "Place the pork liver, heart, and kidney in a separate pan. Bring it to a boil over high heat, then reduce the heat and let it simmer for 3-5 minutes until cooked through", "Add the cooked ground pork to the pot of rice porridge. Also add the fish sauce, sugar, salt, and black pepper. Stir well and simmer for 10-15 minutes", "Add the cooked pork offal and let it simmer together for another 5-7 minutes", "Ladle the porridge into bowls and garnish with chopped scallions and cilantro. If desired, top with fried garlic, fried shallots, sliced chili peppers, and lime wedges"]
    },
    {
        "Ingredients": ["2 cups broken rice", "3 cups water", "1/2 lb pork chops", "2 tablespoons vegetable oil", "1 small onion, chopped", "2 cloves garlic, chopped", "2 tablespoons oyster sauce", "2 tablespoons soy sauce", "1 teaspoon sugar", "1/2 teaspoon salt", "1/4 teaspoon black pepper", "Shredded lettuce", "Sliced cucumber", "Sliced tomato", "Pickled vegetables (optional)", "Fried egg (optional)"],
        "Steps": ["Rinse the broken rice with cold water until the water runs clear. In a pot, add 3 cups of water and rice and bring it to a boil. Reduce heat to low, cover and simmer for 15-20 minutes until rice is fully cooked", "In a pan, heat up oil over medium-high heat. Add onion and garlic and sauté until fragrant", "Add the pork chops to the pan and cook for 4-5 minutes on each side until browned", "In a mixing bowl, mix together oyster sauce, soy sauce, sugar, salt and black pepper. Brush the mixture onto the pork chops and let them cook for an additional 1-2 minutes until fully coated", "Remove the pork chops from the pan and let them rest for a few minutes before slicing thinly", "Assemble the dish by placing a serving of cooked rice on each plate. Arrange the sliced pork chops, lettuce, cucumber, tomato, pickled vegetables (if using), and fried egg (if using) on top of the rice", "Serve hot with extra sauce on the side"]
    },
    {
        "Ingredients": ["10-12 rice paper wrappers", "1/2 lb cooked shrimp, sliced in half lengthwise", "1/2 cup cooked pork, sliced into thin strips", "1/2 cup rice vermicelli noodles, cooked and drained", "1 cup lettuce leaves, shredded", "1 cup fresh herbs (cilantro, mint, and/or Thai basil)", "1/2 cup bean sprouts", "10-12 fresh chives or basil leaves", "Hoisin sauce and/or peanut sauce, for dipping"],
        "Steps": ["Prep all the ingredients by slicing the cooked shrimp in half lengthwise, slicing the cooked pork into thin strips, shredding the lettuce leaves, and rinsing the fresh herbs and bean sprouts", "Soak one rice paper wrapper in warm water for 10-15 seconds or until it becomes pliable and slightly sticky", "Lay the wrapper flat on a damp towel. Place two shrimp halves, a small amount of pork, vermicelli noodles, lettuce, fresh herbs, and bean sprouts near the bottom edge of the wrapper", "Fold the bottom edge of the wrapper over the filling, tuck in the sides, and roll the wrapper tightly away from you, making sure the filling is tightly packed inside", "Repeat with the remaining ingredients until all the filling is used up", "Serve the spring rolls with hoisin sauce and/or peanut sauce for dipping"]
    },
    {
        "Ingredients": ["1 lb pork bones", "1 lb pork shoulder, cut into thin slices", "1 tablespoon vegetable oil", "1 small onion, chopped", "2 cloves garlic, chopped", "1 tablespoon fish sauce", "1 tablespoon soy sauce", "1 teaspoon sugar", "1/2 teaspoon salt", "1/4 teaspoon black pepper", "8 cups water", "1 package of dried Hu Tieu noodles (about 14 ounces), soaked in cold water for 1 hour prior to cooking", "1 cup bean sprouts", "1/2 cup chopped green onions", "1/4 cup chopped cilantro", "Lime wedges", "Sliced chili peppers (optional)"],
        "Steps": ["In a large pot, bring pork bones and water to a boil. Reduce heat to simmer and cook for 30-40 minutes. Skim any impurities occasionally", "While the broth is cooking, in another pan, heat up oil over medium-high heat. Add onion and garlic and sauté until fragrant", "Add the sliced pork shoulder to the pan and cook until browned", "Add fish sauce, soy sauce, sugar, salt and black pepper into the pan. Stir until well combined and set aside", "Strain the broth to remove any remaining impurities. Bring the broth back to a boil", "Add the soaked noodle into a colander and drain the water. Add the noodles to the boiling broth and cook for around 2-3 minutes, or until the noodles soften", "Put a serving of noodles into a bowl. Add the pork slices onto one side of the bowl and top with sprouts, green onions, cilantro, and sliced chili peppers (if desired)", "Pour the hot and fragrant broth over the top of the noodles", "Serve with lime wedges on the side"]
    },
    {
        "Ingredients": ["1 lb pork shoulder", "1 tablespoon vegetable oil", "1 small onion, chopped", "2 cloves garlic, chopped", "1 tablespoon fish sauce", "1 tablespoon soy sauce", "1 tablespoon sugar", "1/2 tablespoon turmeric powder", "1/2 teaspoon chili flakes", "1/2 teaspoon salt", "1/4 teaspoon black pepper", "8 cups water or chicken broth", "1 package of Quang-style noodles (about 14 ounces)", "1 cup bean sprouts", "1/2 cup chopped lettuce", "1/2 cup chopped mint", "1/2 cup chopped cilantro", "Lime wedges", "Sliced chili peppers (optional)"],
        "Steps": ["In a large pot, bring water or chicken broth and pork shoulder to a boil. Reduce heat to simmer and cook for 30-40 minutes. Skim any impurities occasionally", "While the broth is cooking, in another pan, heat up oil over medium-high heat. Add onion and garlic and sauté until fragrant", "Add the pork shoulder to the pan and cook until browned", "Add fish sauce, soy sauce, sugar, turmeric powder, chili flakes, salt and black pepper into the pan. Stir until well combined and set aside", "Strain the broth to remove any remaining impurities. Bring the broth back to a boil", "Add the Quang-style noodles into a colander and rinse with cool water. Add the noodles to the boiling broth and cook for around 2-3 minutes, or until the noodles soften. Remove the noodles and place in individual bowls", "Add the pork slices on top of the noodles. Ladle the hot broth over the top of the pork and noodles", "Top with bean sprouts, chopped lettuce, mint, cilantro, and sliced chili peppers (if desired)", "Serve with lime wedges on the side"]
    },
    {
        "Ingredients": ["1 lb ground pork (lean)", "1/2 cup cooked sticky rice", "1/4 cup sugar", "1/4 cup fish sauce", "1/4 cup vinegar", "1/4 cup chopped garlic", "1/2 cup chopped chives", "1/2 cup chopped cilantro", "1/2 teaspoon black pepper", "2 Thai chili peppers, chopped (optional)", "1 pack of banana leaves (optional)"],
        "Steps": ["In a mixing bowl, combine ground pork, cooked sticky rice, sugar, fish sauce, vinegar, garlic, chives, cilantro, black pepper, and chopped chili peppers (if using). Mix until well combined", "Cover the bowl with a plastic wrap and refrigerate for 2-3 days, allowing the mixture to fully ferment", "Once fermented, divide the mixture into small portions and roll into cylindrical shapes (about the length of a finger). Optional: wrap the rolls in banana leaves and tie the ends with string to secure the rolls", "Place the rolls in a covered container and refrigerate for another day to allow the flavors to meld together", "Slice and serve the rolls thinly as a snack or appetizer"]
    },
    {
        "Ingredients": ["2 lbs beef bones", "1 tablespoon vegetable oil", "1 small onion, peeled and quartered", "2 inches of fresh ginger, sliced", "1 cinnamon stick", "3 star anise", "3 cloves", "1 tablespoon coriander seeds", "1 tablespoon fennel seeds", "1 tablespoon sugar", "1 tablespoon fish sauce", "1 teaspoon salt", "1 package of dried pho noodles (about 14 ounces), soaked in cold water for 1 hour prior to cooking", "1/2 lb beef sirloin, sliced thinly", "1/4 cup chopped cilantro", "1/4 cup chopped green onions", "Lime wedges", "Bean sprouts", "Thai basil leaves", "Sliced chili peppers (optional)"],
        "Steps": ["Preheat the oven to 425°F. Place the beef bones on a baking sheet and roast for 30 minutes, or until browned", "While the bones are roasting, in a large pot, heat up vegetable oil over medium-high heat. Add onion and ginger and sauté until fragrant", "Add the roasted beef bones into the pot and add enough water to cover the bones. Bring the water to a boil and reduce heat to simmer for around 3-4 hours. Skim any impurities occasionally", "While the broth is simmering, in a dry pan, toast the cinnamon stick, star anise, cloves, coriander seeds, and fennel seeds until fragrant. Add the spices to the pot with the broth", "Add sugar, fish sauce, and salt into the pot. Continue to simmer for another hour", "Strain the broth to remove any remaining impurities and spices. Bring the broth back to a boil and keep it hot", "Add the soaked pho noodles into a colander and drain the water. Divide the noodles evenly among individual bowls", "Place a few slices of raw beef onto the noodles in each bowl", "Pour the hot broth over the beef and noodles. The hot broth will cook the beef slices", "Top with cilantro, green onions, bean sprouts, Thai basil leaves, and sliced chili peppers (if desired)", "Serve with lime wedges on the side"]
    },
    {
        "Ingredients": ["2 cups glutinous rice", "1/2 teaspoon turmeric powder", "1/2 teaspoon salt", "1/2 cup coconut milk", "1/4 cup sugar", "1/4 cup roasted mung bean", "1/4 cup shredded dried coconut", "Banana leaves"],
        "Steps": ["Rinse the glutinous rice with cold water a few times until the water runs clear. Soak the rice in water for at least 3 hours, or overnight", "Drain the rice and transfer to a steamer basket. Add turmeric powder and salt and stir to combine", "Steam the rice for around 20-25 minutes, or until the rice is fully cooked and soft", "In a saucepan, combine coconut milk and sugar over medium heat. Stir until the sugar is fully dissolved. Set aside", "In a dry pan, toast the shredded coconut and roasted mung bean over medium heat until fragrant. Set aside", "Once the rice is cooked, transfer it to a mixing bowl. While the rice is still hot, pour in the coconut milk mixture and stir until the rice is evenly coated", "On a flat surface, place a banana leaf and lightly brush with oil. Spread a layer of the cooked rice over the banana leaf. Sprinkle a layer of toasted shredded coconut and roasted mung bean on top of the rice", "Use another banana leaf to cover the rice and filling, and press down gently to flatten. Repeat this process with additional layers of rice and filling until all the ingredients are used up", "Once finished, wrap the banana leaves around the sticky rice and press down to form a rectangular shape", "Cut the xoi xeo into small rectangular or square pieces, and serve warm as a delicious and sweet snack"]
    },
]

FOOD_NAME = [
    'Bánh bèo', 'Bánh bột lọc', 'Bánh căn', 'Bánh canh', 'Bánh chưng', 
    'Bánh cuốn', 'Bánh đúc', 'Bánh giò', 'Bánh khọt', 'Bánh mì', 'Bánh pía', 'Bánh tét', 'Bánh tráng nướng', 
    'Bánh xèo', 'Bún bò huế', 'Bún đậu mắm tôm', 'Bún mắm', 'Bún riêu', 'Bún thịt nướng', 'Cá kho tộ', 'Canh chua', 
    'Cao lầu', 'cháo lòng', 'Cơm tấm', 'Gỏi cuốn', 'Hủ tiếu', 'Mì quảng', 'Nem chua', 'Phở', 'Xôi xéo'
]
